### ISSUE TITLE
[정인] 24.03.18 TODO

### ISSUE THREAD

**Issue by silverpoodle** [cca-ffodregamdi/running-hi-back-v2#65]
## 오늘의 할 일 💚

- [x] Post PR 리뷰사항 수정
- [x] Post_Keyword 복합키 수정
- [ ] @transactional 문제 해결

## 참고할만한 자료(선택)
- https://techblog.woowahan.com/2595/
