### ISSUE TITLE
[김종완] 2024.03.18 TODO

### ISSUE THREAD

**Issue by Subak-Uncle** [cca-ffodregamdi/running-hi-back-v2#67]
## 오늘의 할 일 💚

- [x] 북마크, 댓글 도메인 테스트 코드 작성 > 03.19
- [ ] 신고된 댓글 리스트 조회 기능 개발 > 03. 19
- [ ] POSTMAN으로 테스트 문서화 > 03.19
- [x] NotFound 회의
