### ISSUE TITLE
[수의] 2024.03.19 TODO

### ISSUE THREAD

**Issue by numerical43** [cca-ffodregamdi/running-hi-back-v2#75]
## 오늘의 할 일 💚

- [x] Member 필터 테스트 코드 
- [x] Member jwtTokenProvider 테스트 코드
- [ ] Feedback 빌더 수정

**Comment by Subak-Uncle** [comment]
👀
👄
